### ISSUE TITLE
Fix MacOS/BSD specific commands

### ISSUE THREAD

**Issue by eureka-cpu** [Cloud-Scythe-Labs/nix-watch#4]
There's some differences between the Linux and MacOS versions of common commands (echo -e for instance doesn't seem to work), so there needs to be a way to tell nix-watch before build time what variation of command it should use for which system. This should be fairly straight forward since things are working already on Linux, it's just a matter of sorting out how they will work on MacOS.

What isn't working:
- [x] Terminal does not clear when `-c` is passed, but manually running the command `clear` does. This may be an issue in relation to the argument parser.
- [x] Debug logs do not print when `--debug` is passed (likely due to the `-e` arg passed to MacOS's version of `echo`)
- [x] MacOS uses a different version than the Linux `stat`, so unless you run `nix develop` and acquire `stat` from the nix store, it fails to update the modification timestamp.
- [x] Making changes to files seems to only trigger a new process once, and without the above debug logging it's difficult to tell why this is. If I had to guess it could have something to do with `stat` as well since it's a darwin dependency and not linux.

There may be other things not working but this is what I've found so far. Currently testing this on my M1 Macbook Pro (`aarch64-darwin`) with nix version 2.22

**Comment by eureka-cpu** [comment]
@sezna I've figured out 3 of the 4 issues above, any idea what would be causing it to only recognize that changes were made once? The program still loops but does nothing after the first pass. Works perfectly on Linux, this is just on MacOS.

**Comment by sezna** [comment]
In the man page for `stat` on MacOS (the BSD one), there's a `-x` flag that prints its output in in a more compatible way with Linux's `stat`. Did you give that a whirl? I haven't dug into your code, but that might be a good starting point.

**Comment by eureka-cpu** [comment]
> In the man page for `stat` on MacOS (the BSD one), there's a `-x` flag that prints its output in in a more compatible way with Linux's `stat`. Did you give that a whirl? I haven't dug into your code, but that might be a good starting point.

`stat` seems to be working as expected, I added the GNU `coreutils` package version of `stat` as a dependency. Since this will only ever be used as a dev-tool, and by people using nix it shouldn't be a problem. The same goes for `echo`, `pwd`, `getopt`, and `clear`.

**Comment by eureka-cpu** [comment]
After many debug statements, I've found that indeed `stat` is working correctly so it isn't that.

Some things to note:
- the `last_mod_time` variable which is outside of the loop and tracks whether to start another process for some reason doesn't get updated until the second process runs. So order of ops is:
  - start nix-watch
  - command runs, sees `last_mod_time` is 0 (this is the value it's initialized at), updates it (debugs show that it does indeed get updated)
  - command finishes
- save the file to proc the fswatch and start the next iteration, it then shows that the `last_mod_time` is 0 and updates it again.....
- this time it actually does update it, but then this happens:
  - the `last_mod_time` is no longer 0, it's always 1722837808, _always_... the `stat` that's included on the system by default shows the same thing:
  ```sh
  stat -f %m . 
  1722837808
  ```
- then from there, it always returns from the function until `fswatch` detects anther update but the `stat` time never changes.

**Comment by eureka-cpu** [comment]
I've figured out that MacOS doesn't update the directory modification timestamp if one of its files' timestamp is updated. If I add a `touch $WATCH_DIR` then it will continue to pick up the new timestamp, but this causes an infinite loop. It also doesn't solve the problem of updating the `last_mod_time` variable. For some reason that's now always 0 for every process that runs.

**Comment by eureka-cpu** [comment]
One solution that comes to mind is to use some other file to track the last known modification time, since we don't get that from the directory that has files changing in it, and the modification time variable won't update. If we touch some other file and check that for the timestamp that might work.
